//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class MainConfiguration : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainConfiguration defaultInstance = ((MainConfiguration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainConfiguration())));
        
        public static MainConfiguration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasUserDoneSetup {
            get {
                return ((bool)(this["HasUserDoneSetup"]));
            }
            set {
                this["HasUserDoneSetup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ALERTS_CPUTrackingEnable {
            get {
                return ((bool)(this["ALERTS_CPUTrackingEnable"]));
            }
            set {
                this["ALERTS_CPUTrackingEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ALERTS_MemoryTrackingEnable {
            get {
                return ((bool)(this["ALERTS_MemoryTrackingEnable"]));
            }
            set {
                this["ALERTS_MemoryTrackingEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("explorer")]
        public string ALERTS_TrackProcess {
            get {
                return ((string)(this["ALERTS_TrackProcess"]));
            }
            set {
                this["ALERTS_TrackProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableRounding {
            get {
                return ((bool)(this["EnableRounding"]));
            }
            set {
                this["EnableRounding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Theme {
            get {
                return ((int)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CLEANENGINE_CustomPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CLEANENGINE_CustomPaths"]));
            }
            set {
                this["CLEANENGINE_CustomPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ALERTS_EnableTrackProcess {
            get {
                return ((bool)(this["ALERTS_EnableTrackProcess"]));
            }
            set {
                this["ALERTS_EnableTrackProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DISKS_ShowHiddenDrives {
            get {
                return ((bool)(this["DISKS_ShowHiddenDrives"]));
            }
            set {
                this["DISKS_ShowHiddenDrives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CLEANENGINE_ExportLog {
            get {
                return ((bool)(this["CLEANENGINE_ExportLog"]));
            }
            set {
                this["CLEANENGINE_ExportLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string CLEANENGINE_CustomSource {
            get {
                return ((string)(this["CLEANENGINE_CustomSource"]));
            }
            set {
                this["CLEANENGINE_CustomSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CLEANENGINE_EnableCustomSource {
            get {
                return ((bool)(this["CLEANENGINE_EnableCustomSource"]));
            }
            set {
                this["CLEANENGINE_EnableCustomSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ALERTS_CPUTrackingLimit {
            get {
                return ((int)(this["ALERTS_CPUTrackingLimit"]));
            }
            set {
                this["ALERTS_CPUTrackingLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoSurfScapeGateway {
            get {
                return ((bool)(this["EnableAutoSurfScapeGateway"]));
            }
            set {
                this["EnableAutoSurfScapeGateway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GraphicRenderingMode {
            get {
                return ((int)(this["GraphicRenderingMode"]));
            }
            set {
                this["GraphicRenderingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoStartup {
            get {
                return ((bool)(this["AutoStartup"]));
            }
            set {
                this["AutoStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableLegacyPowerPlans {
            get {
                return ((bool)(this["EnableLegacyPowerPlans"]));
            }
            set {
                this["EnableLegacyPowerPlans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveSidebarCompactMode {
            get {
                return ((bool)(this["SaveSidebarCompactMode"]));
            }
            set {
                this["SaveSidebarCompactMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SidebarCompactMode {
            get {
                return ((bool)(this["SidebarCompactMode"]));
            }
            set {
                this["SidebarCompactMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseShouldMinimize {
            get {
                return ((bool)(this["CloseShouldMinimize"]));
            }
            set {
                this["CloseShouldMinimize"] = value;
            }
        }
    }
}
