//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class MainConfiguration : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainConfiguration defaultInstance = ((MainConfiguration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainConfiguration())));
        
        public static MainConfiguration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasUserDoneSetup {
            get {
                return ((bool)(this["HasUserDoneSetup"]));
            }
            set {
                this["HasUserDoneSetup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSchoolFeatures {
            get {
                return ((bool)(this["EnableSchoolFeatures"]));
            }
            set {
                this["EnableSchoolFeatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ALERTS_CPUTrackingEnable {
            get {
                return ((bool)(this["ALERTS_CPUTrackingEnable"]));
            }
            set {
                this["ALERTS_CPUTrackingEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ALERTS_MemoryTrackingEnable {
            get {
                return ((bool)(this["ALERTS_MemoryTrackingEnable"]));
            }
            set {
                this["ALERTS_MemoryTrackingEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("explorer.exe")]
        public string ALERTS_TrackProcess {
            get {
                return ((string)(this["ALERTS_TrackProcess"]));
            }
            set {
                this["ALERTS_TrackProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableRounding {
            get {
                return ((bool)(this["EnableRounding"]));
            }
            set {
                this["EnableRounding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Steel WPF Dark")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CLEANENGINE_CustomPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CLEANENGINE_CustomPaths"]));
            }
            set {
                this["CLEANENGINE_CustomPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ALERTS_EnableTrackProcess {
            get {
                return ((bool)(this["ALERTS_EnableTrackProcess"]));
            }
            set {
                this["ALERTS_EnableTrackProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DISKS_ShowHiddenDrives {
            get {
                return ((bool)(this["DISKS_ShowHiddenDrives"]));
            }
            set {
                this["DISKS_ShowHiddenDrives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CLEANENGINE_ExportLog {
            get {
                return ((bool)(this["CLEANENGINE_ExportLog"]));
            }
            set {
                this["CLEANENGINE_ExportLog"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://surfscape.github.io/celer/signatures/cleaning.json")]
        public string CLEANENGINE_DefaultSource {
            get {
                return ((string)(this["CLEANENGINE_DefaultSource"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string CLEANENGINE_CustomSource {
            get {
                return ((string)(this["CLEANENGINE_CustomSource"]));
            }
            set {
                this["CLEANENGINE_CustomSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CLEANENGINE_AllowCustomSource {
            get {
                return ((bool)(this["CLEANENGINE_AllowCustomSource"]));
            }
            set {
                this["CLEANENGINE_AllowCustomSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ALERTS_CPUTrackingLimit {
            get {
                return ((int)(this["ALERTS_CPUTrackingLimit"]));
            }
            set {
                this["ALERTS_CPUTrackingLimit"] = value;
            }
        }
    }
}
