//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Celer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Celer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient Checker.
        /// </summary>
        public static string AmbientChecker {
            get {
                return ResourceManager.GetString("AmbientChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a small check to see what system tools are currently available for Celer..
        /// </summary>
        public static string AmbientChecker_Description {
            get {
                return ResourceManager.GetString("AmbientChecker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Done!.
        /// </summary>
        public static string AmbientChecker_DoneLabel {
            get {
                return ResourceManager.GetString("AmbientChecker_DoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Verification.
        /// </summary>
        public static string AmbientChecker_StartLabel {
            get {
                return ResourceManager.GetString("AmbientChecker_StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for an internet connection.
        /// </summary>
        public static string GatewayTask_CheckInternetConnection {
            get {
                return ResourceManager.GetString("GatewayTask_CheckInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t retrieve signatures. Trying to get local signatures instead..
        /// </summary>
        public static string GatewayTask_CheckLocalSignatures {
            get {
                return ResourceManager.GetString("GatewayTask_CheckLocalSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures updated.
        /// </summary>
        public static string GatewayTask_CleaningSignaturesUpdated {
            get {
                return ResourceManager.GetString("GatewayTask_CleaningSignaturesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signatures found, cleaning has been disabled..
        /// </summary>
        public static string GatewayTask_DisableCleaning {
            get {
                return ResourceManager.GetString("GatewayTask_DisableCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading cleaning signatures.
        /// </summary>
        public static string GatewayTask_DownloadCleaningSignatures {
            get {
                return ResourceManager.GetString("GatewayTask_DownloadCleaningSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run dxDiag.
        /// </summary>
        public static string GatewayTask_FailDxDiag {
            get {
                return ResourceManager.GetString("GatewayTask_FailDxDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found local signatures.
        /// </summary>
        public static string GatewayTask_FoundLocalSignatures {
            get {
                return ResourceManager.GetString("GatewayTask_FoundLocalSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Celer.
        /// </summary>
        public static string GatewayTask_StartCeler {
            get {
                return ResourceManager.GetString("GatewayTask_StartCeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting hardware services.
        /// </summary>
        public static string GatewayTask_StartHardwareServices {
            get {
                return ResourceManager.GetString("GatewayTask_StartHardwareServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string MainWindow_GoBackTooltip {
            get {
                return ResourceManager.GetString("MainWindow_GoBackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App Menu.
        /// </summary>
        public static string MainWindow_MenuTooltip {
            get {
                return ResourceManager.GetString("MainWindow_MenuTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ambient Checker.
        /// </summary>
        public static string Menu_AmbientChecker {
            get {
                return ResourceManager.GetString("Menu_AmbientChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preferences.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cleaning.
        /// </summary>
        public static string Menu_View_Cleaning {
            get {
                return ResourceManager.GetString("Menu_View_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dashboard.
        /// </summary>
        public static string Menu_View_Dashboard {
            get {
                return ResourceManager.GetString("Menu_View_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Maintenance.
        /// </summary>
        public static string Menu_View_Maintenance {
            get {
                return ResourceManager.GetString("Menu_View_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Privacy &amp; Security.
        /// </summary>
        public static string Menu_View_Opsec {
            get {
                return ResourceManager.GetString("Menu_View_Opsec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Optimization.
        /// </summary>
        public static string Menu_View_Optimization {
            get {
                return ResourceManager.GetString("Menu_View_Optimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically update signatures on launch.
        /// </summary>
        public static string Onboarding_AutoDownloadsCheckboxLabel {
            get {
                return ResourceManager.GetString("Onboarding_AutoDownloadsCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update signatures when Celer is launching up without the need of manually updating them from the Tools menu..
        /// </summary>
        public static string Onboarding_AutoDownloadsCheckboxTooltip {
            get {
                return ResourceManager.GetString("Onboarding_AutoDownloadsCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start with Windows.
        /// </summary>
        public static string Onboarding_AutoStartupCheckboxLabel {
            get {
                return ResourceManager.GetString("Onboarding_AutoStartupCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Celer to auto start with Windows. This enables you to use Celer Quick Center on the system tray..
        /// </summary>
        public static string Onboarding_AutoStartupCheckboxTooltip {
            get {
                return ResourceManager.GetString("Onboarding_AutoStartupCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (can be later changed in the settings).
        /// </summary>
        public static string Onboarding_FeaturesSubheading {
            get {
                return ResourceManager.GetString("Onboarding_FeaturesSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Onboarding_FeaturesTitle {
            get {
                return ResourceManager.GetString("Onboarding_FeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve read and accept the {0} and {1}..
        /// </summary>
        public static string Onboarding_LegalCheckboxLabel {
            get {
                return ResourceManager.GetString("Onboarding_LegalCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string Onboarding_LegalTitle {
            get {
                return ResourceManager.GetString("Onboarding_LegalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celer is a toolbox for Windows 10/11 with the purpose of giving you control over Windows, once again..
        /// </summary>
        public static string Onboarding_WelcomeIntroduction {
            get {
                return ResourceManager.GetString("Onboarding_WelcomeIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Celer!.
        /// </summary>
        public static string Onboarding_WelcomeTitle {
            get {
                return ResourceManager.GetString("Onboarding_WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Onboarding_WindowTitle {
            get {
                return ResourceManager.GetString("Onboarding_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string WaitMessage {
            get {
                return ResourceManager.GetString("WaitMessage", resourceCulture);
            }
        }
    }
}
